#!/bin/bash -e

# Get secrets
user=$(echo $REPO_ACCESS_TOKEN | jq -r .user)
token=$(echo $REPO_ACCESS_TOKEN | jq -r .token)

function fetch_from_gitlab(){
  echo Fetching repository from gitlab

  # Download repo from gitlab api, project version can be version tag (ex v0.1.1) or sha commit or branch name
  curl --header "PRIVATE-TOKEN: $token" \
    "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/repository/archive.zip?sha=$GITLAB_PROJECT_VERSION" \
    -o downloaded_repo.zip

  # Unzip the zipped file
  unzip -o downloaded_repo.zip
  rm downloaded_repo.zip


}

function fetch_from_github(){
  echo Fetching repository from Github
  case $REPO_TYPE in
    private)
      wget --header="Authorization: token $token" --header="Accept:application/vnd.github.v3.raw" \
        -O - https://api.github.com/repos/${REPO_ACCOUNT}/${REPO_NAME}/tarball/${REPO_REFERENCE} | tar xz
    ;;
    public)
      wget --header="Accept:application/vnd.github.v3.raw" \
        -O - https://api.github.com/repos/${REPO_ACCOUNT}/${REPO_NAME}/tarball/${REPO_REFERENCE} | tar xz
    ;;
    *)
    echo Please specify REPO_TYPE environment variable to one of gihub/gitlab
    exit -1
  esac


}

# Main Routine
case $VCS_PROVIDER in

  gitlab )
    fetch_from_gitlab
  ;;

  github )
    fetch_from_github
  ;;

  *)
    echo "Unknown REPO_TYPE, Use One of GITHUB/GITLAB"
    exit -1
  ;;

esac

  # Rename extracted folder name to repo name
  [ -d temp-job ] && rm -rf temp-job
  mkdir temp-job
  dir_name=$(ls -d $REPO_ACCOUNT-$REPO_NAME*)
  echo downloaded directory name is $dir_name
  commit=$(echo $dir_name | sed s/$REPO_ACCOUNT-$REPO_NAME-//g)
  echo Commit Hash is $commit
  export COMMIT_HASH=$commit
  mv  $dir_name temp-job/$WORKSPACE_ID


# Run the script
echo "Running pipeline with Entrypoint arguments $@"
exec ./run-pipeline $@

